### ISSUE TITLE
Change links to Support and Feedback form

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#63]
I get an insecure site warning (see screenshot) when trying to access the Request Support and Provide feedback links in the footer of the app.

<img width="945" alt="screen shot 2018-10-15 at 12 00 28 pm" src="https://user-images.githubusercontent.com/14067061/46926091-a9e4e680-d072-11e8-84f5-4ab691c4f92e.png">

Error says: www.ecocloud.org.au uses an invalid security certificate. The certificate is only valid for ecocloud.org.au.

Can we change the links to go to the secure url?

**Comment by hoylen** [comment]
I know. Solving https://github.com/ausecocloud/ecocloud/issues/49 with WordPress will fix that.

I can go through and edit all the links on the support site to http (and then later change them all back to https once WordPress works properly), but it would certainly be less much effort if #49 can be quickly fixed. Is there anything that prevents Wordpress from being fixed in a reasonably quick time?

**Comment by sarahrichmond** [comment]
@hoylen the Wordpress site should be working properly now.

<img width="1438" alt="screen shot 2018-10-15 at 12 43 54 pm" src="https://user-images.githubusercontent.com/14067061/46927298-01398580-d078-11e8-90c0-9610428c9caa.png">

**Comment by hoylen** [comment]
The WordPress is still not working properly (as of 2018-10-29). It is still using the "no-www" only certificate, instead of the "www and no-www" certificate.

But I have now changed the "https://www.ecocloud.org.au" links to "https://ecocloud.org.au" in the support site. Even when the certificate is fixed, we need to pick one version as the canonical domain name and the other one redirects to it. So let's pick the no-www domain as the canonical domain.

**Comment by hoylen** [comment]
James,

Can you please update the links in the app.ecocloud.org.au pages to go to https://ecocloud.org.au instead of https://www.ecocloud.org.au?

I think that is the only place that still has the www in the domain name of the WordPress site. But if there are others, please change them there also.

Thanks.

Hoylen

**Comment by manhinli** [comment]
> Can you please update the links in the app.ecocloud.org.au pages to go to https://ecocloud.org.au instead of https://www.ecocloud.org.au?

No problem, will do.

**Comment by gweis** [comment]
all links changed

**Comment by manhinli** [comment]
Thanks @gweis - I've also just updated the Keycloak theme to change the links there too: https://github.com/ausecocloud/keycloak_theme/pull/4

**Comment by gweis** [comment]
Thanks @manhinli . Totally forgot about the keycloak theme.
